#!/bin/bash
reset
JOBS=3

TARGET_BRANCH=jan4 
TARGET_HOST=pi6

[ "`uname -m`" == 'x86_64' ] || echo "stop! you have to be an x86" || exit 3

[ "$1" == "" ] || TARGET_HOST=pi5
BLINK_GREEN "target host = $TARGET_HOST"
sleep 3

#----------------------------------------------------------------------------

start_time=`date +%s`
trap stopwatch SIGTERM SIGINT SIGQUIT EXIT 


function stopwatch()
{
   trap - SIGTERM SIGINT SIGQUIT EXIT 
   stop_time=`date +%s`
   exec_time=$(date -u --date @$(($stop_time - $start_time)) +%H:%M:%S)
   echo -e "\n\ntotal time for build = $exec_time \n "
   exit
}

#----------------------------------------------------------------------------
#https://forums.raspberrypi.com/viewtopic.php?t=343387

# Oldbootmnt 
#  final zip file has 2 different layouts depending on deployment strategy
#    - choose yes if you are pasting the zip file into a mounted Pi ISO IMAGE
#    - dont include if you are zippping directly into a live system
#
#----------------------------------------------------------------------------

FINAL_KERNEL_OUT=/home/dwade/public

BLINK_GREEN "target branch $TARGET_BRANCH"

rm -rf $FINAL_KERNEL_OUT/*

tone 500 200 

#$PWD/build-kernel  --branch $TARGET_BRANCH  --menuconfig --noinitramfs --config 5  --jobs $JOBS --unattended   --keep --cross-compile $* --out-dir $FINAL_KERNEL_OUT  | tee build.log
$PWD/build-kernel  --branch $TARGET_BRANCH                --noinitramfs --config 5  --jobs $JOBS --unattended   --keep --cross-compile $* --out-dir $FINAL_KERNEL_OUT  | tee build.log
ret=${PIPESTATUS[0]}

if [ $ret == 0 ]; then
    tone 500 200 2 
    GREEN "see $FINAL_KERNEL_OUT for build output"
    ./kernel2target $TARGET_HOST
    tone 500 200 2 
    tone 700 200 2 

else
    RED "build failed"
fi

exit $ret



