#!/bin/bash

start_time=`date +%s`
trap stopwatch SIGTERM SIGINT SIGQUIT EXIT 

function stopwatch()
{
   trap - SIGTERM SIGINT SIGQUIT EXIT 
   stop_time=`date +%s`
   exec_time=$(date -u --date @$(($stop_time - $start_time)) +%H:%M:%S)
   echo -e "\n\ntotal time for build = $exec_time \n "
}

./doit.sh | tee build.log
